baseURL = 'https://talshachar.github.io/framzn/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'Framzn Hugo'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/' 
    weight = 1
  [[menu.main]]
    identifier = 'product'
    name = 'Product'
    url = '/product/'
    weight = 2
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/blog/'
    weight = 3
